FROM maven:3-jdk-8-slim

WORKDIR /tmp/eschool
COPY . ./

ARG sonar_project_key
ARG sonar_host_url
ARG sonar_login

RUN mvn clean verify sonar:sonar \
  -Dsonar.projectKey=$sonar_project_key \
  -Dsonar.host.url=$sonar_host_url \
  -Dsonar.login=$sonar_login

# ENTRYPOINT ["java"]
# CMD ["-jar", "./app.jar"]
